### ISSUE TITLE
Double Notifications

### ISSUE THREAD

**Issue by jhalvorson6687** [mrthomaschin/CS179J-Team3#35]
When a package is detected and the Pi sends SMS/email notifications, it sends 2 SMS's and 2 emails.

**Comment by Michael-DeSousa** [comment]
Seems to be related to the way we're handling multiprocessing with Python. When the function is run by itself, there are no issues. When a second process is run, we send an additional notification. However, creating a third process still only causes 2 notifications to be sent.

**Comment by Michael-DeSousa** [comment]
Issue was related to running the debugger when starting the flask app. Debugger is no longer turned on and the double notifications have stopped.
