### ISSUE TITLE
Issues separating unit tests from main.c

### ISSUE THREAD

**Issue by cgray09** [mrthomaschin/CS179J-Team3#43]
Had trouble making a file separate from main.c to hold all of the projects unit tests for the atmega that would pass on Travis CI. As for now, decided to leave all of the unit tests in main.c where it is passing in Travis CI.

**Comment by mrthomaschin** [comment]
[6/2] Complete, Makefile and new test_atmega.h file moved into "travis_tests" directory

Modified Makefile SRC
modified #import inside main.c
